[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  BASE_PATH = "/"

[[redirects]]
  from = "/register"
  to = "/"
  status = 302

[[redirects]]
  from = "/register/"
  to = "/"
  status = 302

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
